shell /bin/zsh
# avanzado
term xterm-kitty

# timbre de terminal
enable_audio_bell no

#include red-black-theme.conf

include colors-kitty.conf 

# fuente
font_family        Hack Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size 12.0

confirm_os_window_close 0

# personalización del cursor
# bloque / rayo / subrayado
cursor_shape block
#cursor_blink_interval 0
#cursor_stop_blinking_after 0
shell_integration no-cursor

# gestión de diseño
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stacks

window_padding_width 30

# gestión de pestañas
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab

# Moverse pestañas
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# Portapapeles F1-F2, F3-F4
map f1 copy_to_buffer a
map f2 paste_from_buffer a
map f3 copy_to_buffer b
map f4 paste_from_buffer b

#Bordes
window_margin_width 10
window_padding_width 2.5
resize_in_steps yes

tab_bar_style powerline

background_opacity 0.7

disable_ligatures never

#cursor
cursor_trail 2
cursor_trail_decay 0.2 0.5
cursor_shape beam
cursor_beam_thichness 1.8
cursor_blink_interval 1 ease-in-out
