# vim:ft=kitty

## name:     Base16 Summerfruit Dark
## author:   Christopher Corley (http://christop.club/)
## license:  MIT
## upstream: Adapted from Termite config
## blurb:    Warm and vivid color scheme with strong contrast and deep background.



# The basic colors
foreground              #D0D0D0
background              #090909
selection_foreground    #151515
selection_background    #E0E0E0

# Cursor colors
cursor                  #E0E0E0
cursor_text_color       #151515

# URL underline color when hovering with mouse
url_color               #FF0048

# Kitty window border colors
active_border_color     #ABA800
inactive_border_color   #505050
bell_border_color       #FF0048

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #151515
active_tab_background   #FF0048
inactive_tab_foreground #D0D0D0
inactive_tab_background #202020
tab_bar_background      #151515

# Colors for marks (marked text in the terminal)
mark1_foreground        #151515
mark1_background        #AD00A1
mark2_foreground        #151515
mark2_background        #3777E6
mark3_foreground        #151515
mark3_background        #1FAAAA

# The 16 terminal colors

# black
color0  #151515
color8  #505050

# red
color1  #FF0048
color9  #FF0048

# green
color2  #FF0048
color10 #FF0048

# yellow
color3  #ABA800
color11 #ABA800

# blue
color4  #3777E6
color12 #3777E6

# magenta
color5  #AD00A1
color13 #AD00A1

# cyan
color6  #1FAAAA
color14 #1FAAAA

# white
color7  #D0D0D0
color15 #FFFFFF

