# See: /usr/share/doc/mpd/mpdconf.example

pid_file "/run/mpd/mpd.pid"
db_file "/var/lib/mpd/mpd.db"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
music_directory "/home/isma/a/content/music"

#audio_output {
#    type        "alsa"
#    name        "My ALSA Device"
#    device      "default:2"    # o el dispositivo que uses
#}

audio_output {
    type        "pulse"
    name        "PulseAudio Bluetooth"
    mixer_type  "software" 
}
